# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
# Copyright (C) 1993 - 1995  Microsoft Corporation.  All Rights Reserved.
#
#
# Processor independent makefile

# Nmake macros for building Windows 32-Bit apps
!include <win32.mak>

PROJ = EnhMeta

all: $(PROJ).exe 

#
# Define project specific dependencies
#
PROJ_OBJS  = EnhMeta.obj
EXTRA_LIBS = version.lib comctl32.lib
GLOBAL_DEP = resource.h
RC_DEP     = resource.h

#
# Dependencies
#
EnhMeta.obj:	  EnhMeta.c     $(GLOBAL_DEP)

#############################################################################
#
#  There should be no need to modify anything below this line
#

#
# Inference rule for updating the object files
#
.c.obj:
  $(cc) $(cdebug) $(cflags) $(cvars) $*.c
  
.cpp.obj:
  $(cc) $(cdebug) $(cflags) $(cvars) $*.cpp

# Build rule for resource file
$(PROJ).res: $(PROJ).rc $(RC_DEP)
    $(rc) $(rcflags) $(rcvars) /fo $(PROJ).res $(PROJ).rc

# Build rule for EXE
$(PROJ).EXE: $(PROJ_OBJS) $(PROJ).res
    $(link) $(linkdebug) $(guilflags) \
    $(BASE_OBJS) $(PROJ_OBJS) $(PROJ).res $(guilibs) $(EXTRA_LIBS) \
    -out:$(PROJ).exe $(MAPFILE)

# Rules for cleaning out those old files
clean:
    del *.bak 
    del *.pdb 
    del *.obj 
    del *.res 
    del *.exp 
    del *.map 
    del *.sbr 
    del *.bsc

