//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ENHMETA.rc
//
#define IDS_PROGNAME                    1
#define IDS_ABOUTSTRING                 1
#define ID_FILE_OPEN                    100
#define ID_FILE_EXIT                    102
#define ENHMETA_MENU                    400
#define ENHMETA_ICON                    401
#define ENHMETA_ABOUT_DLG               402
#define IDD_METAINFODLG                 403
#define IDD_ABOUTDLG                    404
#define IDD_METARECORDSDLG              405
#define ID_EDIT_COPY                    500
#define ID_EDIT_PASTE                   501
#define ID_EDIT_ORIGINALSIZE            502
#define ID_EDIT_STRETCHTOFIT            503
#define ID_FILE_SAVEENHANCED            504
#define ID_FILE_PRINT                   505
#define ID_EDIT_METAFILEINFO            506
#define ID_FILE_SAVEPLACEABLE           507
#define ID_FILE_SAVEREGULAR             508
#define ID_HELP_ABOUT                   509
#define ID_EDIT_METAFILERECORDS         510
#define IDC_BOUNDTOP                    600
#define IDC_BOUNDLEFT                   601
#define IDC_BOUNDRIGHT                  602
#define IDC_BOUNDBOTTOM                 603
#define IDC_FRAMETOP                    604
#define IDC_FRAMELEFT                   605
#define IDC_FRAMERIGHT                  606
#define IDC_FRAMEBOTTOM                 607
#define IDC_BYTES                       608
#define IDC_RECORDS                     609
#define IDC_HANDLES                     610
#define IDC_PALENTRIES                  611
#define IDC_PIXELSX                     612
#define IDC_MMX                         613
#define IDC_PIXELSY                     614
#define IDC_MMY                         615
#define IDC_DESCRIPTION                 616
#define IDC_ABOUTTEXT                   617
#define IDC_RECORDSLIST                 618
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        406
#define _APS_NEXT_COMMAND_VALUE         511
#define _APS_NEXT_CONTROL_VALUE         620
#define _APS_NEXT_SYMED_VALUE           700
#endif
#endif
